config/routes.rb
MyWeb::Application.routes.draw do

  post 'til', to: 'microposts#create'
  root to: "microposts#index", path: 'til'

  resources :articles, path: 'blog' do
    collection do
      get 'archives'
    end
  end

  resources :users, except: [:show]

  resources :moocs, except: [:show]

  resources :microposts, except: [:show], path: 'til'

  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  resources :sessions, only: [:new, :create, :destroy]

  get 'blog-tags/:tag', to: 'articles#index', as: :articles_tag
  get 'til-tags/:tag', to: 'microposts#index', as: :microposts_tag

  get 'pages', to: 'pages#index'
  post 'pages', to: 'pages#create'
  resources :pages, path: ''

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title, :tag_list
  validates :title, :body, :tag_list, presence: true
  acts_as_taggable
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
  scope :desc, order('created_at DESC')
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, except: [:index, :show, :archives]

  # GET /articles
  # GET /articles.json
  def index
    if params[:tag]
      @tag = params[:tag]
      @articles = Article.desc.tagged_with(@tag).page(params[:page]).per(5)
    else
      @articles = Article.desc.page(params[:page]).per(8)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  def archives
    @articles_year = Article.desc.group_by { |t| t.created_at.beginning_of_year }
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    if request.path != article_path(@article)
      redirect_to @article, status: :moved_permanently and return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
.article
  %h1= link_to article.title, article
  .article-info
    %span.date= date_string(article.created_at, true).html_safe
    - article.tag_list.map do |tag|
      %span.tag= link_to tag, articles_tag_path(tag)
    %sapn.comment-count
      = link_to 'Comments', article_url(article, anchor: 'disqus_thread')
    - if current_user
      %span.pull-right
        = link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary"
        = link_to 'Delete', article, method: :delete,
        data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger"
    -#%p= read_more(article)
  .article-body= markdown(article.body)

app/views/articles/_form.html.haml
= simple_form_for(@article) do |f|
  = f.input :title
  = f.input :body
  = f.input :tag_list, label: "Tags (separated by commas)"
  = f.button :submit

app/views/articles/archive.html.haml
- title "Blog Archive"
%h2 Archives
- @articles_year.each do |date, articles|
  %h3= date.strftime('%Y')
  - articles.each do |article|
    .row.archive
      .col-md-2.text-right= date_string(article.created_at).html_safe
      .col-md-10= link_to article.title, article_path(article)
= link_to 'Back', articles_path

app/views/articles/archives.html.haml
- title "Blog Archive"
%h2 Archives
- @articles_year.each do |date, articles|
  %h3= date.strftime('%Y')
  - articles.each do |article|
    .row.archive
      .col-md-2= date_string(article.created_at).html_safe
      .col-md-8= link_to article.title, article_path(article)
      - if current_user
        .col-md-2.pull-right
          %button.btn.btn-sm.btn-primary= link_to 'Edit', edit_article_path(article)
          %button.btn.btn-sm.btn-danger= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' }
%br

app/views/articles/edit.html.haml
- title "Edit article - #{@article.title}"
%h1 Editing article
= render 'form'
%button.btn.btn-default= link_to 'Show', @article

app/views/articles/index.html.haml
- title "Blog"
- if @tag
  %span.tag-intro= "#{@articles.count} posts tagged with"
  %span.tag= link_to @tag, articles_tag_path(@tag)
- @articles.each do |article|
  = render partial: 'articles/article', locals: { article: article }
= paginate @articles
.text-center
  = link_to(archives_articles_path, class: 'archives') do
    %i.fa.fa-archive.fa-2x{'data-toggle' => 'tooltip', 'title' => 'ARCHIVES'}

app/views/articles/new.html.haml
- title "New Article"
%h1 New article
= render 'articles/form'
= link_to 'Back', articles_path

app/views/articles/show.html.haml
- title "Blog- #{@article.title}"
= render partial: 'articles/article', locals: { article: @article }
#disqus_thread
:javascript
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'chuntaolu'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
.back
  = link_to articles_path do
    = fa_icon 'long-arrow-left', text: "Back"