config/routes.rb
MyWeb::Application.routes.draw do

  post 'til', to: 'microposts#create'
  root to: "microposts#index", path: 'til'

  resources :articles, path: 'blog' do
    collection do
      get 'archives'
    end
  end

  resources :users, except: [:show]

  resources :moocs, except: [:show]

  resources :microposts, except: [:show], path: 'til'

  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  resources :sessions, only: [:new, :create, :destroy]

  get 'blog-tags/:tag', to: 'articles#index', as: :articles_tag
  get 'til-tags/:tag', to: 'microposts#index', as: :microposts_tag

  get 'pages', to: 'pages#index'
  post 'pages', to: 'pages#create'
  resources :pages, path: ''

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :tag_list, :source_link
  validates :content, :tag_list, presence: true
  acts_as_taggable
  extend FriendlyId
  friendly_id :date, use: [:slugged, :history]
  scope :desc, order('created_at DESC')

  def date
    (created_at || Time.now).strftime '%F'
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :require_login, except: [:index]

  # GET /microposts
  # GET /microposts.json
  def index
    if params[:tag]
      @tag = params[:tag]
      @microposts = Micropost.desc.tagged_with(@tag).page(params[:page]).per(10)
    else
      @microposts = Micropost.desc.page(params[:page]).per(10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(params[:micropost])

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to microposts_path, notice: 'Micropost was successfully created.' }
        format.json { render json: @micropost, status: :created, location: @micropost }
      else
        format.html { render action: "new" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to microposts_path, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.haml
= simple_form_for(@micropost) do |f|
  = f.input :content
  = f.input :tag_list, label: "Tags (separated by commas)"
  = f.input :source_link
  = f.submit

app/views/microposts/_micropost.html.haml
.micropost
  .micropost-info.well
    %span.date= date_string(micropost.created_at, true).html_safe
    - micropost.tag_list.map do |tag|
      %span.tag= link_to tag, microposts_tag_path(tag)
    - if micropost.source_link.present?
      %a.source-link{href: micropost.source_link, 'data-toggle' => "tooltip", title: "source", target: '_blank'}
        = fa_icon "external-link lg"
    - if current_user
      %span.pull-right
        = link_to "Edit", edit_micropost_path(micropost), class: 'btn btn-xs btn-primary'
        = link_to 'Delete', micropost, method: :delete,
          data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'
  .micropost-body.well= markdown(micropost.content)

app/views/microposts/edit.html.haml
- title "Edit micropost - #{date_string(@micropost.created_at)}"
%h1 Edit micropost
= render 'form'
= link_to 'Back', microposts_path

app/views/microposts/index.html.haml
- title "Microposts"
.til-title
  %span.til-head= link_to 'Today I learned', microposts_path
  - if @tag
    %span.tag-intro= "#{@microposts.count} tagged with"
    %sapn.tag= link_to @tag, microposts_tag_path(@tag)
.til-sub little bits of gold I picked up here and there everyday
- @microposts.each do |micropost|
  = render partial: 'microposts/micropost', locals: { micropost: micropost }
= paginate @microposts

app/views/microposts/new.html.haml
- title 'New Micropost'
%h1 New micropost
= render 'form'
= link_to 'Back', microposts_path