config/routes.rb
MyWeb::Application.routes.draw do

  post 'til', to: 'microposts#create'
  root to: "microposts#index", path: 'til'

  resources :articles, path: 'blog' do
    collection do
      get 'archives'
    end
  end

  resources :users, except: [:show]

  resources :moocs, except: [:show]

  resources :microposts, except: [:show], path: 'til'

  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  resources :sessions, only: [:new, :create, :destroy]

  get 'blog-tags/:tag', to: 'articles#index', as: :articles_tag
  get 'til-tags/:tag', to: 'microposts#index', as: :microposts_tag

  get 'pages', to: 'pages#index'
  post 'pages', to: 'pages#create'
  resources :pages, path: ''

end

app/views/layouts/_flash_messages.html.haml
- flash.each do |type, message|
  %div{class: "alert #{bootstrap_class_for(type)} fade in"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/layouts/_footer.html.haml
#footer
  .container
    .icons
      = link_to t('footer_links.github_url'), target: '_blank' do
        = fa_icon "github-square 2x"
      = link_to t('footer_links.linkedin_url'), target: '_blank'  do
        = fa_icon "linkedin-square 2x"
      = link_to t('footer_links.twitter_url'), target: '_blank'  do
        = fa_icon "twitter-square 2x"
    %p.text-muted
      %span= '&copy;&nbsp;2014, Chuntao Lu'.html_safe
    %p.text-muted
      %span= "Powered by #{link_to 'Ruby on Rails', t('footer_links.ror_url'), target: '_balnk'}".html_safe
      |
      %span= "Hosted on #{link_to 'Heroku', t('footer_links.heroku_url'), target: '_blank'}".html_safe
:javascript
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'chuntaolu'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function () {
      var s = document.createElement('script'); s.async = true;
      s.type = 'text/javascript';
      s.src = '//' + disqus_shortname + '.disqus.com/count.js';
      (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
  }());

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand.lg
        = link_to(root_path) do
          .logo
            .logo-c
            .logo-l
      -#= link_to "Chuntao Lu", root_path, class: "navbar-brand"
    #bs-navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.pull-right
        %li{class: active?(microposts_path)}
          = link_to "TIL", microposts_path
        %li{class: active?(articles_path)}
          = link_to "Blog", articles_path
        %li{class: active?(moocs_path)}
          = link_to 'Mooc', moocs_path
        - ['projects', 'about'].each do |page_name|
          - if Page.exists? page_name
            %li{class: active?(page_path(page_name))}
              = link_to page_name.capitalize, page_path(page_name)
        - if current_user
          %li.dropdown
            %button.btn.btn-sm.btn-success
              Admin
            %ul.dropdown-menu
              %li= link_to "Pages", pages_path
              %li= link_to "Users", users_path
              %li= link_to "New Til", new_micropost_path
              %li= link_to "New Post", new_article_path
              %li.divider
              %li= link_to "Log out", logout_path
    .navbar-shadow

app/views/layouts/application.html.haml
%html
  %head
    %title= yield(:title) || "Chunto LU"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
  %body
    #wrap
      .container
        = render 'layouts/navbar'
        = render partial: 'layouts/flash_messages', flash: flash
        = yield
      -#%a.glyphicon.glyphicon-chevron-up{href: '#'}
    = render 'layouts/footer'